id = 1
host = "127.0.0.1"
port = 8901
data_path = "/var/lib/cnosdb/meta"
cluster_name = "cluster_xxx"
grpc_enable_gzip = false
lmdb_max_map_size = 1024000000
heartbeat_interval = 3000
raft_logs_to_keep = 10000
install_snapshot_timeout = 3600000
send_append_entries_timeout = 5000
usage_schema_cache_size = 2097152 # 2MiB
cluster_schema_cache_size = 2097152 # 2MiB

[log]
level = "info"
path = "/var/log/cnosdb"

[heartbeat]
heartbeat_recheck_interval = 300
heartbeat_expired_interval = 600
