id = 2
host = "127.0.0.1"
port = 8911

snapshot_path = "/tmp/cnosdb/meta/snapshot"
journal_path = "/tmp/cnosdb/meta/journal"
snapshot_per_events = 500

[log]
level = "info"
path = "/tmp/cnosdb/logs"

[meta_init]
cluster_name = "cluster_xxx"
admin_user = "root"
system_tenant = "cnosdb"
default_database = ["public", "usage_schema"]

[heartbeat]
heartbeat_recheck_interval = 300
heartbeat_expired_interval = 600