[package]
name = "tskv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.1"
core_affinity = "0.5.10"
crossbeam = "0.8.1"
snafu = "0.7"
tokio = "1.17.0"
protos = { path = "../protos" }
