[package]
name = "tskv"
version.workspace = true
edition.workspace = true

[dependencies]
config = { path = "../config" }
meta = { path = "../meta" }
models = { path = "../common/models" }
metrics = { path = "../common/metrics" }
protos = { path = "../common/protos", features = ["test"] }
trace = { path = "../common/trace" }
utils = { path = "../common/utils" }
error_code = { path = "../common/error_code" }
lru_cache = { path = "../common/lru_cache" }
memory_pool = { path = "../common/memory_pool" }

async-recursion = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
bzip2 = { workspace = true }
chrono = { workspace = true }
core_affinity = { workspace = true }
crc32fast = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
datafusion = { workspace = true }
evmap = { workspace = true }
flatbuffers = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true, features = ["std", "thread-pool"] }
integer-encoding = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true }
minivec = { workspace = true }
mio = { workspace = true }
num_cpus = { workspace = true }
num_enum = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
page_size = { workspace = true }
parking_lot = { workspace = true, features = ["nightly", "send_guard"] }
priority-queue = { workspace = true }
q_compress = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
sled = { workspace = true }
snafu = { workspace = true }
snap = { workspace = true }
static_assertions = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
walkdir = { workspace = true }
zstd = { workspace = true }
radixdb = { version = "0.2.5", features = ["custom-store"] }
roaring = "0.10.1"
lru = "0.9.0"
rand = { workspace = true }

[target.'cfg(any(target_os = "linux"))'.dependencies]
tokio-uring = { version = "0.4", optional = true }
rio = { version = "0.9", optional = true }

[features]
default = []
io_uring = ["rio"]

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
rand = { workspace = true }
tempfile = { workspace = true }
parking_lot = { workspace = true, features = ["nightly"] }


[[bench]]
name = "kvcore_bench"
harness = false
