[global]
node_id = 2001
host = "localhost"
cluster_name = 'cluster_xxx'
store_metrics = true

[deployment]
# mode = 'query_tskv'
# cpu = 8
# memory = 16

[meta]
service_addr = ["127.0.0.1:8901"]
report_time_interval = "30s"
usage_schema_cache_size = "2MiB"
cluster_schema_cache_size = "2MiB"

[query]
max_server_connections = 10240
query_sql_limit = "16M"  # 16777216
write_sql_limit = "160M" # 167772160
auth_enabled = false
read_timeout = "3000ms"
write_timeout = "3000ms"
stream_trigger_cpu = 1
stream_executor_cpu = 2
sql_record_timeout = "10s"

[storage]
# Directory for summary: $path/summary/
# Directory for index: $path/index/$database/
# Directory for tsm: $path/data/$database/tsm/
# Directory for delta: $path/data/$database/delta/
path = '/tmp/cnosdb/2001/db'
max_summary_size = "128MiB"            # 134217728
base_file_size = "16MiB"               # 16777216
flush_req_channel_cap = 16
max_cached_readers = 32
compact_trigger_file_num = 4
compact_trigger_cold_duration = "1h"
max_compact_size = "2GiB"              # 2147483648
max_concurrent_compaction = 4
collect_compaction_metrics = false
strict_write = false
reserve_space = "0"
copyinto_trigger_flush_size = "128MiB" # 134217728
max_datablock_size = "100KiB"
index_cache_capacity = 100000

[wal]
path = '/tmp/cnosdb/2001/wal'
max_file_size = "1GiB"                 # 1073741824
sync = false
compress = "zstd"

[cache]
max_buffer_size = "512MiB" # 536,870,912
partition = 16           # default memcache partition number

[log]
level = 'info'
path = '/tmp/cnosdb/2001/log'
max_file_count = 10
file_rotation = "daily"

[security]
# [security.tls_config]
# certificate = "./config/tls/server.crt"
# private_key = "./config/tls/server.key"

[service]
http_listen_port = 8912
grpc_listen_port = 8913
grpc_enable_gzip = false
flight_rpc_listen_port = 8914
tcp_listen_port = 8915
vector_listen_port = 8916
enable_report = true


[cluster]
raft_logs_to_keep = 5000
snapshot_holding_time = "3600s"
lmdb_max_map_size = "1024000000B"
heartbeat_interval = "3000ms"
trigger_snapshot_interval = "600s"
install_snapshot_timeout = "3600000ms"
send_append_entries_timeout = "5000ms"

# [trace]
# auto_generate_span = true
# otlp_endpoint = 'http://localhost:4317'
