[global]
node_id = 1001
host = "localhost"
cluster_name = 'cluster_xxx'
store_metrics = true

[deployment]
# mode = 'query_tskv'
# cpu = 8
# memory = 16

[meta]
service_addr = ["127.0.0.1:8901"]
report_time_interval_secs = 30

[query]
max_server_connections = 10240
query_sql_limit = 16777216     # 16 * 1024 * 1024
write_sql_limit = 167772160    # 160 * 1024 * 1024
auth_enabled = false
read_timeout_ms = 3000
write_timeout_ms = 3000
stream_trigger_cpu = 1
stream_executor_cpu = 2

[storage]
# Directory for summary: $path/summary/
# Directory for index: $path/index/$database/
# Directory for tsm: $path/data/$database/tsm/
# Directory for delta: $path/data/$database/delta/
path = '/tmp/cnosdb/1001/db'
max_summary_size = "128M"            # 134217728
base_file_size = "16M"               # 16777216
flush_req_channel_cap = 16
max_cached_readers = 32
compact_trigger_file_num = 4
compact_trigger_cold_duration = "1h"
max_compact_size = "2G"              # 2147483648
max_concurrent_compaction = 4
strict_write = false
reserve_space = "0"
copyinto_trigger_flush_size = "128M" # 134217728

[wal]
enabled = true
path = '/tmp/cnosdb/1001/wal'
wal_req_channel_cap = 64
max_file_size = "1G"                 # 1073741824
flush_trigger_total_file_size = "2G" # 2147483648
sync = false
sync_interval = "0"

[cache]
max_buffer_size = "512M" # 536,870,912
partition = 16          # default memcache partition number

[log]
level = 'info'
path = '/tmp/cnosdb/1001/log'

[security]
# [security.tls_config]
# certificate = "./config/tls/server.crt"
# private_key = "./config/tls/server.key"

[service]
http_listen_port = 8902
grpc_listen_port = 8903
grpc_enable_gzip = false
flight_rpc_listen_port = 8904
tcp_listen_port = 8905
vector_listen_port = 8906
enable_report = true


[cluster]
raft_logs_to_keep = 5000
lmdb_max_map_size = 1024000000
heartbeat_interval = 3000
install_snapshot_timeout = 3600000
send_append_entries_timeout = 5000

# [trace]
# auto_generate_span = false
# [trace.log]
# path = '/var/log/cnosdb'
# [trace.jaeger]
# jaeger_agent_endpoint = 'http://localhost:14268/api/traces'
# max_concurrent_exports = 2
# max_queue_size = 4096
