[query]
max_server_connections = 10240
query_sql_limit = 16777216   # 16 * 1024 * 1024
write_sql_limit = 167772160   # 160 * 1024 * 1024
auth_enabled = false

[storage]
# Directory for summary: $path/summary/
# Directory for index: $path/index/$database/
# Directory for tsm: $path/data/$database/tsm/
# Directory for delta: $path/data/$database/delta/
path = '/tmp/cnosdb/2001/db'
max_summary_size = 134217728 # 128 * 1024 * 1024
base_file_size = 16777216 # 16 * 1024 * 1024
max_level = 4
compact_trigger_file_num = 4
compact_trigger_cold_duration = "1h"
max_compact_size = 2147483648 # 2 * 1024 * 1024 * 1024
max_concurrent_compaction = 4
dio_max_resident = 1024
dio_max_non_resident = 1024
dio_page_len_scale = 1
strict_write = false

[wal]
enabled = true
path = '/tmp/cnosdb/2001/wal'
max_file_size = 1073741824 # 1024 * 1024 * 1024
sync = false

[cache]
max_buffer_size = 134217728 # 128 * 1024 * 1024
max_immutable_number = 4

[log]
level = 'info'
path = '/tmp/cnosdb/2001/log'

[security]
# [security.tls_config]
# certificate = "./config/tls/server.crt"
# private_key = "./config/tls/server.key"

[cluster]
node_id = 2001
tenant = ''
name = 'cluster_xxx'
meta = '127.0.0.1:21001'

http_server = '127.0.0.1:32001'
grpc_server = '127.0.0.1:32002'
tcp_server = '127.0.0.1:32003'
flight_rpc_server = '127.0.0.1:32004'

[hintedoff]
enable = true
path = '/tmp/cnosdb/2001/hh'

