[package]
name = "trace"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../config" }
parking_lot = { workspace = true }
time = { workspace = true , features = ["macros"]}
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["parking_lot", "registry", "env-filter", "time", "local-time",] }
tracing-appender = { workspace = true }
tracing-error = { workspace = true }
color-eyre = { workspace = true }
once_cell = { workspace = true }
console-subscriber = { workspace = true }
async-backtrace = { workspace = true, optional = true }
rand = { workspace = true }
chrono = { workspace = true }

[features]
default = []
backtrace = ["async-backtrace"]