[package]
name = "error_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[workspace]
#members = ["error_code_macro"]

[dependencies]
error_code_macro = {path = "error_code_macro"}
snafu = {workspace = true}
