[package]
name = "query"
version = "0.1.0"
edition = "2021"

[dependencies]
protos = { path = "../../common/protos" }
trace = { path = "../../common/trace" }
tskv = { path = "../../tskv" }
models = { path = "../../common/models" }
utils = { path = "../../common/utils" }
config = { path = "../../config" }
coordinator = { path = "../../coordinator" }
spi = { path = "../spi" }
datafusion = { path = "../../common/datafusion_dep" }
criterion = { version = "0.3.5", features = ["async_tokio"] }
tokio = { version = "1.21", features = ["full"] }
futures = { version = "0.3" }
parking_lot = "0.12"
pin-project = "1.0"
tokio-util = { version = "0.7.0" }
async-trait = "0.1"
rand = "0.8"
chrono = "0.4.22"
crossbeam = "0.8"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.7"
sled = "0.34"
paste = "1.0"
flatbuffers = "2.1"

priority-queue = "1.2.3"
num_cpus = "1"
minivec = "0.4.0"
# use libc on unix like platforms to set worker priority in DedicatedExecutor
[target."cfg(unix)".dependencies.libc]
version = "0.2"

[[bench]]
harness = false
name = "aggregate_function"

[[bench]]
harness = false
name = "scalar_function"
