[package]
name = "spi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models = { path = "../../common/models" }
meta = { path = "../../meta" }
coordinator = { path = "../../coordinator" }
async-trait = { workspace = true }
datafusion = { workspace = true }
snafu = { workspace = true, features = ["backtraces"] }
derive_builder = { workspace = true }
