[package]
name = "spi"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../config" }
coordinator = { path = "../../coordinator" }
derive_traits = { path = "../../common/derive_traits" }
meta = { path = "../../meta" }
models = { path = "../../common/models" }
protocol_parser = { path = "../../common/protocol_parser" }
protos = { path = "../../common/protos" }
trace = { path = "../../common/trace" }
tskv = { path = "../../tskv" }
utils={ path = "../../common/utils" }

arrow-flight = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
datafusion = { workspace = true }
derive_builder = { workspace = true }
duration-str = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
object_store = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true, features = ["backtrace"] }
snap = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
