[package]
name = "utils"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trace = { path = "../trace" }

fnv = { workspace = true }
siphasher = { workspace = true }
twox-hash = { workspace = true }

async-backtrace = { workspace = true, optional = true }
futures = { workspace = true }
libc = { workspace = true }
serde = { version = "1.0.171", features = ["derive"] }
tokio = { workspace = true, features = ["full", "tracing"] }

[target.'cfg(unix)'.dependencies]
pprof = { workspace = true, features = ["flamegraph", "protobuf-codec", "frame-pointer"] }

[target.'cfg(not(windows))'.dependencies]
tikv-jemalloc-ctl = { version = "0.5", features = ["use_std"] }

[target.'cfg(not(windows))'.dependencies.tikv-jemalloc-sys]
features = ["stats", "profiling", "unprefixed_malloc_on_supported_platforms"]
version = "0.5"

[features]
default = []
backtrace = ["async-backtrace"]

[dev-dependencies]
rand = { workspace = true }
